### ISSUE TITLE
Making each level in the hierarchy "slice-like"

### ISSUE THREAD

**Issue by TianyiShi2001** [nonnominandus/pdbtbx#12]
This will allow semantics that looks more idiomatic for some people, such as:

```rust
for chain in &mut model { // instead of model.chains_mut()
    for residue in &mut chain { // instead of chain.residues_mut()
        ....
    }
}
```

and

```rust
chain[256] = some_residue
```

[The answers to this stackoverflow question] seem to help to achieve this.

**Comment by nonnominandus** [comment]
I like the proposal, but I also really like the possibility of iterating over all levels of organisation (so directly over Atoms from a PDB for example). So I think some extra thought on how to achieve that would be great. I will try and see if a struct can implement IntoIterator multiple times with different Item types. 
And in the best case it would be possible to keep the DoubleEndedIterator, because I needed that one to increase the speed of the parser. As I needed to traverse all atoms to find the right one to extend with an ANISOU (when parsing an ANISOU) but it nearly always is the very last atom.

**Comment by nonnominandus** [comment]
I do not think multiple IntoIterator definitions are possible. So the way it is done now is the idiomatic way of having multiple 'view's over the structs (as done in String for example). We could think of having the immediate level below the struct available as an iterator (eg Iterator<residues> for chains) but I think that does not provide a clear indication of what is happening. 
The same is true for the indexing, it is provided now by a function which specifies the struct result which I think is clear for readers of the code.
But if you think differently please discuss.
