### ISSUE TITLE
Residue serial numbers > 9999

### ISSUE THREAD

**Issue by DocKDE** [nonnominandus/pdbtbx#66]
This probably never comes up when using "regular" PDB files but when solvating a protein (usually with water) it frequently happens that the number of residues exceeds 9999. At first I thought there was a bug in my code but it seems the pdbtbx open_pdb function is to blame. This is the output I get after opening such a PDB file and printing it back to stdout:
```
ATOM      1 N    HIM     1      20.872  37.523  43.475  0.00  0.00           N
ATOM      2 H1   HIM     1      21.537  38.222  43.773  0.00  0.00           H
ATOM      3 H2   HIM     1      21.347  36.635  43.400  0.00  0.00           H
ATOM      4 CA   HIM     1      20.442  37.855  42.095  0.00  0.00           C
ATOM      5 HA   HIM     1      20.697  37.031  41.428  0.00  0.00           H
ATOM      6 CB   HIM     1      18.932  38.092  42.024  0.00  0.00           C
ATOM      7 HB2  HIM     1      18.594  38.695  42.867  0.00  0.00           H
ATOM      8 HB3  HIM     1      18.678  38.597  41.092  0.00  0.00           H
ATOM      9 CG   HIM     1      18.135  36.826  42.056  0.00  0.00           C
ATOM     10 ND1  HIM     1      18.100  35.999  43.156  0.00  0.00           N
ATOM     11 CE1  HIM     1      17.336  34.954  42.900  0.00  0.00           C
ATOM     12 HE1  HIM     1      17.192  34.166  43.639  0.00  0.00           H
ATOM     13 NEM  HIM     1      16.857  35.084  41.678  0.00  0.00           N
ATOM     14 CD2  HIM     1      17.352  36.239  41.124  0.00  0.00           C
ATOM     15 HD2  HIM     1      17.072  36.495  40.102  0.00  0.00           H
ATOM     16 C    HIM     1      21.229  39.064  41.640  0.00  0.00           C
ATOM     17 O    HIM     1      21.045  40.168  42.148  0.00  0.00           O
ATOM     18 CME  HIM     1      15.954  34.127  41.011  0.00  0.00           C
ATOM     19 HM1  HIM     1      15.474  34.610  40.161  0.00  0.00           H
ATOM     20 HM2  HIM     1      15.192  33.791  41.715  0.00  0.00           H
ATOM     21 HM3  HIM     1      16.527  33.267  40.662  0.00  0.00           H
ATOM  32543 O    HIM     1      11.318  29.317   3.009  0.00  0.00           O
ATOM  32544 H1   HIM     1      11.670  28.720   2.350  0.00  0.00           H
ATOM  32545 H2   HIM     1      10.434  28.992   3.180  0.00  0.00           H
ATOM     22 N    THR     2      22.144  38.833  40.709  0.00  0.00           N
ATOM     23 H    THR     2      22.246  37.909  40.315  0.00  0.00           H
ATOM     24 CA   THR     2      23.072  39.863  40.292  0.00  0.00           C
ATOM     25 HA   THR     2      22.590  40.827  40.129  0.00  0.00           H
ATOM     26 CB   THR     2      24.177  40.038  41.352  0.00  0.00           C
ATOM     27 HB   THR     2      23.704  40.224  42.316  0.00  0.00           H
```

I think what happened is that all residues with serial number > 9999 (all waters in my case) got wrapped around to serial number 1 again and were then appended to the already existing residue with that serial number (retaining the atom serial number). Would it be possible to fix this?
I know that in cases like this there should be an insertion code or something to distinguish residues but unfortunately I have no say in the creating of these files.

**Comment by nonnominandus** [comment]
How does your input file handle this? Does your input file have numbers bigger than 9999? The range of this number is defined by the PDB standard to be 4 characters (page 180 of v3.30) so it is interesting to see how other software handles this limitation. I would like to press again that the mmCIF file format does not have any such limitations (and is fully supported by this library).

**Comment by DocKDE** [comment]
In my input the residue serial numbers also wrap around 9999 and start at 1 again after that but the residues are not reordered. They retain their position in the file and the appropriate residue names and atom serial numbers. 
I realize that the most sensible solution here for me would be switching file formats as mmCIFs seem to be made to address something like this but the quantum chemistry code I'm using doesn't seem to support the format yet (which will hopefully change soon).

**Comment by nonnominandus** [comment]
That makes it clear why PDBTBX gave this result. In reading an atom line the code internally searches for a residue matching the given serial number and insertion code and adds the atom to this residue, this is in line with the definition of the PDB format (v3.30).
```
Alphabet letters are commonly used for insertion code. The insertion code is used when two
residues have the same numbering. The combination of residue numbering and insertion code
defines the unique residue.
```
_PDB File Format v. 3.3 - Page 177_

So given this definition the program that created the input is not creating valid PDB files. If you have a way we could use to detect these kinds of problems (maybe with extra user input in a function somewhere) and which generates the result you want, maybe it just keeps counting upwards so go to 10001 instead of 1, I would be happy to include that in the library. But for that we need a clear description of the behavior we want and need to keep in mind what the next program using the resulting PDB files will make of it.

Possibly I could build something which detects when the serial number wraps around and adds an extra factor 10000 each time it does this. For this to be active I would want a user to explicitly ask for this (something like an extra option in opening). The result of this will not be valid to save as a PDB file unless the serial number is taken mod 10000 again. So in the best case the resulting file would be saved as a mmCIF file, to prevent problems like this in the next program opening the file.

To be very clear I do not really like solutions like this, because this goed outside the definition of PDB files, but at the same time I understand that many programs use PDB files in a way not supported by the official definition so I get that it can be a problem worth solving.

**Comment by DocKDE** [comment]
I see. Amber does indeed write invalid PDB in that respect, strange that it does this.
While it might be possible to "solve" the issue as you described, this might also break compatibility with other programs parsing the resulting file. I won't request you do that since the use seems quite limited, I'll have a look if I can find another solution with actually valid PDB files or mmCIF files first.

**Comment by nonnominandus** [comment]
Okay, good luck! If it in the end is the easiest if the above solution (or something else) is implemented in this library feel free to reopen this issue (or create a new one of course).

**Comment by DocKDE** [comment]
So it took me a minute to manually add insertion codes and thus circumvent the issue entirely. I think it's fine for this issue to remain closed for the time being :)

**Comment by nonnominandus** [comment]
Okay I implemented your proposal, only for that I needed to revamp the saving system for PDBs which leaves me with some errors right now. But I need some sleep so will continue tomorrow I think. Very short: I needed to build a way to force fields to be of a certain width, either by padding with spaces or cropping off the extraneous parts. I rewrote all PDB lines to use this new function, but somewhere a couple of spaces are off. ‾\(o.o)/‾
